config/routes.rb
Rails.application.routes.draw do

    # Route our idex page to the recipes controller
    root 'recipes#index'
    
    # Routs for ingredients and instructions as nested resources.
    resources :recipes do
        resources :ingredients
        resources :instructions
    end

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  
  # Relate to the Recipe model
  belongs_to :recipe
  
  # Valide that we have a name
  validates :name, presence: true
  
end

app/models/instruction.rb
class Instruction < ActiveRecord::Base
  
  # Relate to the Recipe model
  belongs_to :recipe
  
  # Valide that we have a description
  validates :description, presence: true
  
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
    
    # Mount the uploader class generated with carrierwave.
    mount_uploader :image, ImageUploader
    
    # Relate ingredients and instructions to the Recipe model.
    has_many :ingredients, dependent: :destroy
    has_many :instructions, dependent: :destroy
    
    # Some validation for the title and description.
    validates :title, presence: true, length: { minimum: 5 }
    validates :description, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
    
    def create
        @recipe = Recipe.find(params[:recipe_id])
        @ingredient = @recipe.ingredients.create(ingredient_params)
        # When I create a new ingredient, I wanted it to redirect back to the edit page.
        # This way I can keep all editing of associated ingredients on one page.
        redirect_to edit_recipe_path(@recipe)
    end
    
    def destroy
        @recipe = Recipe.find(params[:recipe_id])
        @ingredient = @recipe.ingredients.find(params[:id])
        @ingredient.destroy
        # When I delete a new ingredient, I wanted it to redirect back to the edit page.
        # This way I can keep all editing of associated ingredients on one page.
        redirect_to edit_recipe_path(@recipe)
    end
  
    private
        def ingredient_params
            params.require(:ingredient).permit(:name)
        end
end

app/controllers/instructions_controller.rb
class InstructionsController < ApplicationController
    
    def create
        @recipe = Recipe.find(params[:recipe_id])
        @instruction = @recipe.instructions.create(instruction_params)
        # When I create a new instruction, I wanted it to redirect back to the edit page.
        # This way I can keep all editing of associated instruction on one page.
        redirect_to edit_recipe_path(@recipe)
    end
    
    def destroy
        @recipe = Recipe.find(params[:recipe_id])
        @instruction = @recipe.instructions.find(params[:id])
        @instruction.destroy
        # When I delete a new instruction, I wanted it to redirect back to the edit page.
        # This way I can keep all editing of associated instruction on one page.
        redirect_to edit_recipe_path(@recipe)
    end
  
    private
        def instruction_params
            params.require(:instruction).permit(:description)
        end
        
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    
    def index
        # Pagination provided by will_paginate & will_paginate-bootstrap gems. Also
        # ordering DESC to put the most recent recipe at the top of my list.
        @recipes = Recipe.all.paginate(:page => params[:page], :per_page => 5).order(id: :DESC)
    end
    
    def show
        @recipe = Recipe.find(params[:id])
    end
  
    def new
        @recipe = Recipe.new
    end
    
    def edit
        @recipe = Recipe.find(params[:id])
    end
        
    def create
        @recipe = Recipe.new(recipe_params)
        
        if @recipe.save
            # render the edit view so we can add ingredients and instruction. This is
            # kind of hack since I don't know how to build formsets like in Django.
            render 'edit', notice: "Successfully created recipe."
        else
            render 'new'
        end
    end
    
    def update
        @recipe = Recipe.find(params[:id])
        
        if @recipe.update(recipe_params)
            redirect_to @recipe, notice: "Successfully updated recipe."
        else
            render 'edit'
        end
    end
    
    def destroy
        @recipe = Recipe.find(params[:id])
        @recipe.destroy
 
        redirect_to recipes_path
    end
    
    private
        def recipe_params
            params.require(:recipe).permit(:title, :image, :description, :servings, :prep_time, :cook_time, :passive_time)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/instructions_helper.rb
module InstructionsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/ingredients/_form.html.erb
<div class="modal fade" id="ingredientModal" tabindex="-1" role="dialog" aria-labelledby="ingredientModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="ingredientModalLabel">Add Ingredient</h4>
            </div>
            <%= form_for([@recipe, @recipe.ingredients.build]) do |f| %>
            <div class="modal-body">
                <div class="form-group">
                    <%= f.text_field :name, :class => 'form-control' %>
                </div>
                <div class="form-group text-right">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <%= f.submit 'Add', :class => 'btn btn-primary' %>
                </div>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/ingredients/_ingredient.html.erb
<li class="list-group-item">
    <%= link_to '<i class="fa fa-minus-circle"></i>'.html_safe,
        [ingredient.recipe, ingredient], method: :delete, 
        data: { confirm: 'Are you sure you want to dellete this ingredient?' }, 
        :title => "delete ingredient" %> 
    <%= ingredient.name %> 
</li>

app/views/instructions/_form.html.erb
<div class="modal fade" id="instructionModal" tabindex="-1" role="dialog" aria-labelledby="instructionModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="instructionModalLabel">New Instruction</h4>
            </div>
            <%= form_for([@recipe, @recipe.instructions.build]) do |f| %>
            <div class="modal-body">
                <div class="form-group">
                    <%= f.text_area :description, :class => 'form-control' %>
                </div>
                <div class="form-group text-right">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <%= f.submit 'Add', :class => 'btn btn-primary' %>
                </div>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/instructions/_instruction.html.erb
<li class="list-group-item"> 
    <%= link_to '<i class="fa fa-minus-circle"></i>'.html_safe,
        [instruction.recipe, instruction], method: :delete, 
        data: { confirm: 'Are you sure you want to dellete this instruction?' }, 
        :title => "delete instruction" %> 
    <%= instruction.description %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <%= csrf_meta_tags %>
        <title>Diner</title>
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
        <% # Wanted to try out including a remote stylesheet. %>
        <%= stylesheet_link_tag 'application', 'https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css', media: 'all' %>
    </head>
    <body>
        <% if flash[:notice] %>
            <div id="global-alert" class="alert alert-info text-center" role="alert">
                <strong>Notice!</strong> <%= flash[:notice] %>
            </div>
        <% end %>
        <%= yield %>
        
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <script type="text/javascript">
            $(document).ready(function () {
                window.setTimeout(function() {
                    $(".alert").fadeTo(1000, 0).slideUp(500, function(){
                        $(this).remove(); 
                    });
                }, 3000);
                $('.recipe-list li').click(function(){
                    if($(this).hasClass( "highlight")){
                        $(this).removeClass('highlight');
                    } else {
                        $(this).addClass('highlight');
                    }
                });
            });
        </script>
    </body>
</html>

app/views/recipes/_edit_form.html.erb
    <% # Render the primary recipe form %>
    <%= form_for @recipe, :html => {:class => 'form-horizontal',:multipart => true} do |f| %>
        <% if @recipe.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@recipe.errors.count, "error") %> prohibited this article
                from being saved:
            </h2>
            <ul>
                <% @recipe.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
        <% end %>
        <div class="form-group">
            <%= f.label :title, :class => 'control-label' %>
            <%= f.text_field :title, :class => 'form-control' %>
        </div>
        <div class="form-group">
            <%= f.label :image, :class => 'control-label' %>
            <%= f.file_field :image, :class => 'form-control' %>
            <% unless @recipe.image.blank? %>
            <em><small>Current image... <%= @recipe.image %></small></em>
            <% end %>
        </div>
        <div class="form-group">
            <%= f.label :description, :class => 'control-label' %>
            <%= f.text_area :description, :class => 'form-control' %>
        </div>
        <div class="row">
            <div class="col-md-5">
                <div class="form-group">
                    <%= f.label :servings, :class => 'control-label' %>
                    <%= f.number_field :servings, :class => 'form-control' %>
                </div>
                <div class="form-group">
                    <%= f.label :prep_time, :class => 'control-label' %>
                    <%= f.number_field :prep_time, :class => 'form-control' %>
                </div>
            </div>
            <div class="col-md-2"></div>
            <div class="col-md-5">
                <div class="form-group">
                    <%= f.label :cook_time, :class => 'control-label' %>
                    <%= f.number_field :cook_time, :class => 'form-control' %>
                </div>
                <div class="form-group">
                    <%= f.label :passive_time, :class => 'control-label' %>
                    <%= f.number_field :passive_time, :class => 'form-control' %>
                </div>
            </div>
        </div>
        
        <div class="row flush-col">
            <% # Render the associated ingredients and link to modal form %>
            <div class="page-header">
                <h4><a href="#" data-toggle="modal" data-target="#ingredientModal" title="add ingredient"><i class="fa fa-plus-circle"></i></a> Ingredients</h4>
            </div>
            <ul class="list-group">
                <% unless @recipe.ingredients.blank? %>
                <%= render @recipe.ingredients %>
                <% else %>
                <li class="list-group-item text-warning"><strong>NO INGREDIENTS</strong></li>
                <% end %>
            </ul>
            <% # Render the associated instructions and link to modal form %>
            <div class="page-header">
                <h4><a href="#" data-toggle="modal" data-target="#instructionModal" title="add instruction"><i class="fa fa-plus-circle"></i></a> Instructions</h4>
            </div>
            <ul class="list-group">
                <% unless @recipe.instructions.blank? %>
                <%= render @recipe.instructions %>
                <% else %>
                <li class="list-group-item text-warning"><strong>NO INSTRUCTIONS</strong></li>
                <% end %>
            </ul>
        </div>
        
        <div class="form-group text-right">
            <%= link_to 'Delete Recipe',recipe_path(@recipe),method: :delete, 
                data: { confirm: 'Are you sure you want to delete this recipe?' }, :class => "btn btn-danger" %>
                
            <%= f.submit 'Save Recipe', :class => 'btn btn-primary' %>
        </div>
    <% end %>
    
    <%= render 'ingredients/form' %>
    <%= render 'instructions/form' %>

app/views/recipes/_footer.html.erb
<footer class="footer">
    <div class="container">
        <p class="text-center text-muted">
            &copy; 2016 iKnowMac, inc. All rights reserved.
        </p>
    </div>
</footer>

app/views/recipes/_new_form.html.erb
<div class="">
    <% # Render the recipe new_form %>
    <%= form_for @recipe, :html => {:class => 'form-horizontal',:multipart => true} do |f| %>
        <% if @recipe.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@recipe.errors.count, "error") %> prohibited this article
                from being saved:
            </h2>
            <ul>
                <% @recipe.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
        <% end %>
        
        <div class="form-group">
            <%= f.label :title, :class => 'control-label' %>
            <%= f.text_field :title, :class => 'form-control' %>
        </div>
        <div class="form-group">
            <%= f.label :image, :class => 'control-label' %>
            <%= f.file_field :image, :class => 'form-control' %>
        </div>
        <div class="form-group">
            <%= f.label :description, :class => 'control-label' %>
            <%= f.text_area :description, :class => 'form-control' %>
        </div>
        <div class="form-group">
            <%= f.label :servings, :class => 'control-label' %>
            <%= f.number_field :servings, :class => 'form-control' %>
        </div>
        <div class="form-group">
            <%= f.label :prep_time, :class => 'control-label' %>
            <%= f.number_field :prep_time, :class => 'form-control' %>
        </div>
        <div class="form-group">
            <%= f.label :cook_time, :class => 'control-label' %>
            <%= f.number_field :cook_time, :class => 'form-control' %>
        </div>
        <div class="form-group">
            <%= f.label :passive_time, :class => 'control-label' %>
            <%= f.number_field :passive_time, :class => 'form-control' %>
        </div>
        
        <div class="form-group text-right">
            <%= f.submit 'Save Recipe', :class => 'btn btn-primary' %>
        </div>
    <% end %>
</div>

app/views/recipes/edit.html.erb
<div class="container">
    
    <div class="page-header">
        <h1>
            <%= link_to '<i class="fa fa-arrow-circle-left"></i>'.html_safe, 
                recipes_path, :title => "go back" %> 
            <%= @recipe.title %>
        </h1>
    </div>
    
    <div class="col-sm-8">
        <% # Render the edit_form which DOES include associated models delete links. %>
        <%= render 'edit_form' %>
    </div>
    
    <div class="col-sm-4 text-center" style="margin-top:20px;">
        <img src="http://lorempixel.com/300/600/food/advertising" width="300" height="600" />
    </div>
    
</div>

<%= render "footer" %>

app/views/recipes/index.html.erb
<video autoplay loop poster="/static/cookies.jpg" id="bgvid">
    <source src="polina.webm" type="video/webm">
    <source src="/static/cookies.mp4" type="video/mp4">
</video>
<div class="container">
    <% # This is a hack to get ONLY the style for the index page loaded. There is %>
    <% # probably a better way. %>
    <%= stylesheet_link_tag params[:controller] %>    
    <div class="vertical-center">
        <div class="col-md-3 col-xs-1"></div>
        <div class="col-md-6 col-xs-10">
            <h1 class="add-recipe text-center"><a href="/recipes/new"><span>Recipes</span></a></h1>
            <div class="list-group">
                <% @recipes.each do |recipe| %>
                <%= link_to recipe.title, recipe_path(recipe), class: "list-group-item" %>
                <% end %>
            </div>
            <div class="text-center">
                <%= will_paginate @recipes, renderer: BootstrapPagination::Rails %>
            </div>
        </div>
        <div class="col-md-3 col-xs-1"></div>
    </div>
    
</div>

app/views/recipes/new.html.erb
<div class="container">
    
    <div class="page-header">
        <h1>
            <%= link_to '<i class="fa fa-arrow-circle-left"></i>'.html_safe, 
                recipes_path, :title => "go back" %> 
            Add Yours
        </h1>
    </div>
    
    <div class="col-sm-8">
        <% # Render the new_form which DOES NOT include associated models delete links. %>
        <%= render 'new_form' %>
    </div>
    
    <div class="col-sm-4 text-center" style="margin-top:20px;">
        <img src="http://lorempixel.com/300/600/food/advertising" width="300" height="600" />
    </div>

</div>

<%= render "footer" %>

app/views/recipes/show.html.erb
<div class="container">
    
    <div class="page-header">
        <h1>
            <%= link_to '<i class="fa fa-arrow-circle-left"></i>'.html_safe, 
                recipes_path, :title => "go back" %> 
            <%= @recipe.title %> 
            <small>
            <%= link_to '<i class="fa fa-edit"></i>'.html_safe, 
                edit_recipe_path(@recipe), :title => "edit recipe" %>
            </small>
        </h1>
    </div>
    
    <div class="col-sm-8">
        <% if @recipe.image_url(:large) %>
        <%= image_tag @recipe.image_url(:large), :class => "img-responsive img-rounded" %><br/>
        <% end %>
        <p class="lead"><%= @recipe.description %></p>
        <% unless @recipe.ingredients.blank? %>
        <h4>Ingredients</h4>
        <ul class="list-group recipe-list">
            <% @recipe.ingredients.each do |ingredient| %>
            <li class="list-group-item"><%= ingredient.name %></li>
            <% end %>
        </ul>
        <% end %>
        <% unless @recipe.instructions.blank? %>
        <h4>Instructions</h4>
        <ul class="list-group recipe-list">
            <% @recipe.instructions.each do |instruction| %>
            <li class="list-group-item"><%= instruction.description %></li>
            <% end %>
        </ul>
        <% end %>
    </div>
    
    <div class="col-sm-4 text-center">
        <img src="http://lorempixel.com/300/600/food/advertising" width="300" height="600" />
    </div>

</div>

<%= render "footer" %>